"""jax#1606 -- per-sample conv gradients: compile scales with the SAMPLE COUNT, runtime does not.

    https://github.com/jax-ml/jax/issues/1606          no maintainer diagnosis in thread

Reported 2019, CPU (the reporter had no GPU), x64 on, L=4, N_symm=8, out_chan=1, filter 2x2,
VALID, N_points=300:

    first call (compile + run)   163.3030 s
    every later call              0.0002-0.0003 s

a compile/runtime ratio of roughly 5e5. The reporter's own observation is the load-bearing one:
XLA's "Very slow compile" alarm starts firing above ~300 samples and is quiet below it.

MECHANISM, confirmed by lowering this file on CPU at N=25 and N=100 before committing it. `evaluate`
is traced for ONE sample, so `grad(evaluate)` is a single-sample filter gradient, and `vmap` has to
push the batch axis through `conv_general_dilated`'s transpose w.r.t. the FILTER. The natural thing
would be to map the new axis onto the convolution's existing N dimension -- a conv already has a
batch dimension and it is already free. But per-sample filter gradients are not summable over N:
each sample must keep its own kernel. So the batching rule cannot reuse the N dimension. What it
does instead is visible in the StableHLO, and it is the ground truth this case exists to hand to an
attribution tool -- ONE instruction, and the pathological integer is written on its face:

    N=25   %19 = stablehlo.convolution(...) {feature_group_count = 25  : i64}
                 (tensor<200x1x4x4xf64>, tensor<8x25x3x3xf64>)  -> tensor<25x1x2x2xf64>
    N=100  %19 = stablehlo.convolution(...) {feature_group_count = 100 : i64}
                 (tensor<800x1x4x4xf64>, tensor<8x100x3x3xf64>) -> tensor<100x1x2x2xf64>

`feature_group_count` IS the sample count. The forward conv next door stays at
feature_group_count=1. And the module is 32 MLIR lines at BOTH sizes -- the program handed to XLA
does not grow at all, only that one attribute does. So whatever compile cost appears here cannot be
explained by program size, which is exactly the property that makes it a good attribution test and
exactly the property that defeats instruction counting. The suspected consumer is XLA's grouped-
convolution expansion, which splits a G-group conv into G slices when no library kernel covers it;
that would be O(N) HLO generated by the compiler, after the point where anything user-visible was
measured.

WHY THIS CASE EARNS ITS PLACE. The corpus has zero coverage of `conv_general_dilated`, and this is
the only conv report with a stated COMPILE number -- the other conv issues (#12868, #26266, #23783,
#30469) are runtime or cuDNN algorithm selection, not compile. It is also a different failure shape
from everything we have: the pathology is not in the user's program at all, it is in ONE batching
rule, and the fix is a rewrite of the same maths. An attribution tool that can only point at source
lines will point at `evaluate`, which is three lines long and innocent; the answer is "the vmap of
the transpose", which lives in jax's own conv batching rule.

WHAT THE CONTROLS ISOLATE. Two axes, and the case needs both.

  * FORMULATION (`*_control`): `grad(evaluate)(params, whole_batch)` -- the gradient of the summed
    batch loss instead of N per-sample gradients. Because `evaluate` reshapes its input to
    (-1, 1, L, L) before convolving, the SAME function body serves both arms unchanged: pass it one
    sample and it convolves 8 images, pass it the batch and it convolves 8N. Same conv, same data,
    same FLOPs to within a constant, no vmap. Compile should be flat in N. Nothing differs between
    the arms but the transform, so anything the sweep shows is the transform.
  * SCALE (the sweep, N = 25/100/300/1000): the claim under test is literally "compile time is a
    function of an integer that should not appear in it". One point cannot say that; four can. 300
    is the reporter's threshold, 25 is well below it, 1000 well above.

The third arm, `conv_persample_nojit_1000`, drops the inner `jit(grad(...))` from inside the vmap
(the issue body has this as a commented-out line). Nesting a jit inside a vmap has its own known
cost in modern jax -- the inner jit stays a closed call that the batching rule must push through --
so this separates "vmap of grad of conv is slow" from "vmap of jit is slow", which are different
findings and would want different fixes.

UNCERTAIN, and this is the honest state of it: 163 s is a 2019 CPU number on a jax seven years
older than 0.10.2. The feature_group_count=N structure above survives in 0.10.2 -- that much is
verified -- but whether XLA still pays O(N) to compile it is not, and it may handle the grouped conv
directly, in which case the case retires with a clean negative, which is a result. On GPU the
behaviour is entirely unverified: a grouped f64 convolution has no cuDNN kernel, so XLA may fall
back to a generic emitter whose compile cost is worse than the 2019 CPU number rather than better,
or cuDNN algorithm picking may dominate the first call and be misread as compile. Sizes are tiny
(N=1000 is a 1 MB batch), so the sweep is cheap to run even if it turns out flat.

PORTED from the 2019 source: `from jax.config import config` -> harness sets x64 globally;
`jax.experimental.stax.GeneralConv` (removed) -> `lax.conv_general_dilated` called directly with
the same dimension_numbers/out_chan/filter/strides/padding; `np.int` (removed) -> int; glorot
initialisation reproduced with numpy. Everything numeric matches the issue.
"""

from __future__ import annotations

import functools

import jax
import jax.numpy as jnp
import numpy as np
from jax import lax

L = 4  # linear image dimension, from the issue
N_SYMM = 2 * 2 * 2  # 8 symmetry images per sample, from the issue
OUT_CHAN = 1
FILTER_SHAPE = (2, 2)
STRIDES = (1, 1)
DIMENSION_NUMBERS = ("NCHW", "OIHW", "NCHW")

N_POINTS = (25, 100, 300, 1000)  # 300 is where the reporter's "Very slow compile" alarm starts


def _init_params(seed=1):
    """glorot_normal on OIHW, matching stax's GeneralConv(W_init=glorot_normal(I_ax, O_ax))."""
    rng = np.random.default_rng(seed)
    kh, kw = FILTER_SHAPE
    in_chan = 1
    fan_in = in_chan * kh * kw
    fan_out = OUT_CHAN * kh * kw
    std = np.sqrt(2.0 / (fan_in + fan_out))
    w = rng.standard_normal((OUT_CHAN, in_chan, kh, kw)) * std
    b = np.zeros((1, OUT_CHAN, 1, 1))  # stax bias shape: out_chan on the C axis of out_spec
    return (w, b)


_PARAMS = _init_params()


def _evaluate(params, batch):
    """sum(log(cosh(conv(x)))), verbatim from the issue.

    The reshape to (-1, 1, L, L) is what makes this function serve BOTH arms unchanged: given one
    sample (N_SYMM, L, L) it convolves N_SYMM images, given the whole batch (N, N_SYMM, L, L) it
    convolves N*N_SYMM. Identical HLO up to the leading dimension.
    """
    w, b = params
    x = batch.reshape(-1, 1, L, L)
    a = lax.conv_general_dilated(
        x,
        w,
        window_strides=STRIDES,
        padding="VALID",
        dimension_numbers=DIMENSION_NUMBERS,
    )
    z = jnp.log(jnp.cosh(a + b))
    return jnp.sum(z)


def _persample(batch, params, inner_jit):
    """PATHOLOGICAL: N independent per-sample filter gradients via vmap(grad(...))."""
    g = jax.grad(_evaluate, argnums=0)
    if inner_jit:
        g = jax.jit(g)  # the issue's form: vmap(partial(jit(grad(evaluate)), params))
    return jax.vmap(functools.partial(g, params))(batch)


def _batched(batch, params):
    """CONTROL: one gradient of the summed batch loss. Same conv, same data, no vmap."""
    return jax.grad(_evaluate, argnums=0)(params, batch)


def _batch(n):
    return np.ones((n, N_SYMM, L, L), dtype=np.float64)


CASES = {}

for _n in N_POINTS:
    CASES[f"conv_persample_{_n}"] = (
        functools.partial(_persample, inner_jit=True),
        (_batch(_n), _PARAMS),
        f"jax#1606 vmap(jit(grad(conv))) per-sample filter gradients, N_points={_n}",
    )
    CASES[f"conv_persample_{_n}_control"] = (
        _batched,
        (_batch(_n), _PARAMS),
        f"control: grad of the SUMMED batch loss, same conv/data, no vmap, N_points={_n}; "
        f"this curve should be flat in N",
    )

# Third arm: same thing without the inner jit, to separate "vmap of conv-transpose" from
# "vmap of jit". Only at the largest N -- below the reporter's threshold it tells us nothing.
CASES["conv_persample_nojit_1000"] = (
    functools.partial(_persample, inner_jit=False),
    (_batch(1000), _PARAMS),
    "jax#1606 variant: vmap(grad(conv)) with the inner jit DROPPED (the issue's "
    "commented-out line), N_points=1000",
)
CASES["conv_persample_nojit_1000_control"] = (
    _batched,
    (_batch(1000), _PARAMS),
    "control: grad of the summed batch loss, N_points=1000 (same control as the jit arm, "
    "re-measured so the nojit arm gets its own paired ratio)",
)
